seq_input = "AAGTGCCTCATGTGTCTCCTGATATTAGTCAAGGGTGCGCAACTCTATGAGACCTAGGGACGGTGAAAAACGTTACCTCTAAGCATAAAGTGCGCCCCTGAGCCGGCGGCTTGCATTACGTGAGGCTGTAATGCTAGTCAATATTGGAAACGGCGGAGGACATTGGAGTATACGTGCTGTGGGAGGCCTACACTGCAGAAATCACAGCTCAGCTATTTCGTCTAGGGGACTCACTTGGGGCTTATATATACACCGCGATCTTCTCTTATCCCGGGAATAGCGCGAGACGACGACGGGTACTTTTGGCTACCTGAATCCTTTACAAGGTCTCAACAGACACCAGTCTCGTGTTATTACATGTGCCTAGTCTCGTTCCGACTTCGTCCCTTTAGGGCATCGGGTCTGAGGAGCTCTAAGCGCTGATAGTCAAATTGGTCTTTGTAACACCGGCTAACACCGTGTTTGCGAATTGCGCTCGGGGTCGTAATCCGAGCTGATCCGTGTTTTGGGGCGGCGTAGGACGGCGGTTGATCCGATGCCCATTTCCTTGTCCGACCGGGCCATTCTTCCGTTCACGGATGCCCTTAAAAGAGTCCGTCTCTTGGAGCCTTTTATCTGGCACCCCAAACCATTAGCGCGCGCGCCAGGCCAAGATGTTGAAAATTCACGGTACCTTAGCTGCAGTCTTCGTTCGCAACCGTACTAGCTTCAGGCACCTCTATTGACTACCGGATTGGTTTGAACGTCGTTCCCAGTCCAACGTGAGGACTAGGGACTCCTGTGCGCAGGGGCACAGTGCGTAACTCTTTACAC"

def comp_seq(seq_input):
	comp_seq = []
	sequence = seq_input.upper()

	for letter in sequence:
		if letter == "A":
			comp_seq.append("T")
		elif letter == "T":
			comp_seq.append("A")
		elif letter == "G":
			comp_seq.append("C")
		elif letter == "C":
			comp_seq.append("G")
		elif letter == 'N':
			comp_seq.append("G")
	comp_seq.reverse()
	c_seq = "".join(comp_seq)
	return c_seq



