seq_input = "ATATGACTAGCCTGCATTACCAATGAAACCGATCCATTTGCATCCAATACGAACACACAAGCTCGCTGAATTGTCCCTCGTTGCACCGAGCTGCATTGAAATCAGGTATGTTTGGCGACATAGGCCCTGAGCTTTTTCGTGTCCAGTATGGTAGGCCCTTCGGTAAGTCCTCGAAGCCATATTTCCTCATTACTCACATCGGAGCTCGGGCACCAGGAGGGTGACGAAGCATTAGAAACACCCCAGTAGCTAACGGGTCGTGTCTCGTATATCGCTCGAATAAGAGAGGGTAGGCTGGACGACACTGGATTACCGTGGCGAGATTCTTGAATTGCAACCACGCGAGCCAGTATGGGGTGAAGTACAAGGCCGGTAAAAGGGCCATCTTTGCCGCGCAAACAGTAGTTGTCCAAGACACGCGCCCGTTCCTCCGAAAGTTATTATCAGCAGCCGTTAGTGCTAAGTCCTCACTGCTAGGGAGCCGTATATCCTAGCTACCCGGAAACCTCTATCCCTGCCTGCCACCGCCTCGATATAGAGTCAGCCTCACGCAGTTTGTATGAGATAGTAACCGACACTTGCTCCGGAGATGCAACGCTGACTGTTGGGGAGAAGCAGATCTATGAGGGTGAAGGTCCCCAGGTACGCGACAAAATCAATGTCCGCTATGAAGTGATAATTGTCAGTCGCGATTTCAGGATGGTTGCGTCACTCCAATTGTGGGCGCGAGCATTGGAGAGAGTTTACAGCCTATCATGTCAGCAGGGTGGAGTCTGCCGGTTCGCTCCTCATCCTATCCACACGAGTCTCGGGTCCTGGGCGGGGGATGGAAATCTTAAAACTATGCTTTACGTAACGTTACAGACTGTTACGTATGGGGCCTGATTATCGACTCACGTATGCAGGCGCTGGAGA".upper()
#seq_input = "CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCTGCGGGCAGTAGGTGGAAT".upper()
file = open("exampleseqs.txt", "r")
#file.write(">Rosalind_6404\nCCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCCTCCCACTAATAATTCTGAGG\n>Rosalind_5959\nCCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCTATATCCATTTGTCAGCAGACACGC\n>Rosalind_0808\nCCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCTGCGGGCAGTAGGTGGAAT")
file.close()

def contenter(seq):
	c = 0
	for letter in seq:
		if letter == "G" or letter == "C":
			c += 1
	rv = c/len(seq)

	return round(rv*100,5)
print(contenter(seq_input))


def gccontent(parsed_dic):
	seq_dict = parsed_dic
	gc_list = []
	gc_dic = {}
	c = 0
	for a in seq_dict.keys():
		c = 0
		for letter in seq_dict[a]:
			if letter == "G" or letter == "C":
				c += 1
		gc_list.append(c*100/len(seq_dict[a]))
		gc_dic[a] = c*100/len(seq_dict[a])
	return gc_dic
#print(gccontent())

def maxgetter():
	rdict = gccontent()
	max_value = max(rdict.values())
	for r in rdict.keys():
		if max_value == rdict[r]:
			return r, rdict[r]
#print(maxgetter())
