sequence = "CGGCCACGGTAGCCTAGGGGTGCCAGGTGAACCCCCATGGCGAAGAGCTGCGGACGGGTAGAAGCCTGGCATTACGATATCGATGTATTGTTAACGCATCGGGACCGATCGAGATACAATGGAATACAGGTTCCTCGGGCCATTAATGCTTCCCCCGTGGTTTATAACACTCCTAAACTACTTCTGGATGTCAGTGTCTCGTGATTGTTATACACACATGTACCGTGAGCATATGAACTACGGCTTGATCGACGGGCACTTTCCGTCGCGGAATAGCAGTCACGTCTGATAAAGAGAGATCCGTCGATGTTCAAGGGTTCTAATCACTATGGTGCTTGGCGCCCAGGATTACGCTCTCAACGTATCGACGTCCGACATTATGGGCAGCCCCATGACTGGGAAGAAGACATAACACGAAATTGGGAATTATGGGGCTGCTGTCATGCAAGCGGTAGGCCTCGGATTAGTCGCAGATGAGACTTCTTGAGTCGATGCTAATGAAGTAATACCACCTTTCAACACAGCCTGAAGTCCACATGAGTCAGGATGGATGACACGTAGGTCAAGGTGACATTACACCGTAGAAGCCAGTTCACATCGTCGACATGATTTTCACAGGCGGCGCCAGCTGCTGTGCACGAGCTAACCGCGGTGGCGTGTACTTACTTCTCGGGGACGCGGGCCTTTCCAAACCGACCCTAGCAAAAGAACACAGAACCTAAGCCTCCAAGCCATTCGGATTCTCAACGATTGCGAGGTGAACACTACAGCATTCCTCGGTCTCGCAGATAGTATTGGATAAGCACCACCGATAGGCGTCTGTCAATGTCCGTGTGCGTCAATTTCAAGCGTAGTCAAGATCGGTGGTGAACGGAAACCATGAGCCCGCTTTGTCGGCCAGACGCGGACAATCAAAGATCCCCCGAGGTGGCGACATTCTCAACGCGGCGCTGGGTCTGCCGAACGTGAGGTCATTTAGAGGATGGCGCCTACC"

def Transcription():
	seq_list = []
	for letter in sequence:
		if letter == "T":
			seq_list.append("U")
		else:
			seq_list.append(letter)
	seq = "".join(seq_list)
	
	return seq

def transcription(sequence):
	seq = ''
	dna_seq = 'ATGC'

	for letter in sequence.upper():
		if letter not in dna_seq:
			raise Exception(f'{letter} is not a DNA nucleotide')
		if letter == "T":
			seq += "U"
		else:
			seq += letter

	return seq

print(transcription(sequence))